package com.imooc.nick.cardtestproject.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.imooc.nick.cardtestproject.bean.QuestionInfo;

import com.imooc.nick.cardtestproject.bean.QuestionInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionInfoDaoConfig;

    private final QuestionInfoDao questionInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionInfoDaoConfig = daoConfigMap.get(QuestionInfoDao.class).clone();
        questionInfoDaoConfig.initIdentityScope(type);

        questionInfoDao = new QuestionInfoDao(questionInfoDaoConfig, this);

        registerDao(QuestionInfo.class, questionInfoDao);
    }
    
    public void clear() {
        questionInfoDaoConfig.clearIdentityScope();
    }

    public QuestionInfoDao getQuestionInfoDao() {
        return questionInfoDao;
    }

}
